### ISSUE TITLE
clang on OS X

### ISSUE THREAD

**Issue by mjherold** [ghisvail/pyNFFT#53] opened 2016-05-01 12:32 UTC
clang in OS X does not seem to support openmp. Is there a way to get pyNFFT to work without requiring pfft_threads? Currently I get the following error: "ld: library not found for -lnfft3_threads". The problem is that nfft3 cannot be compiled with the --enable-openmp option under OS X. Is installing gcc with home-brew the only option here?

**Comment by ghisvail** [comment] 2016-05-05 09:29
You'd have to either compile NFFT with a compiler that supports OpenMP, i.e. gcc or a modern clang. Otherwise you can manually edit the setup.py to remove the explicit linkage with nfft3_threads and see how it goes.

**Comment by asarnow** [comment] 2016-05-05 18:19
The easiest thing is to use Homebrew. You can use either GCC (change the makefile to use gcc-5), or clang-omp (change makefile to use clang-omp).

I recommend you install FFTW with Homebrew as well, then compile NFFT and follow the pyNFFT instructions for a non-standard NFFT location.

**Comment by mjherold** [comment] 2016-05-06 07:10
Thank you Daniel! I ended up using gcc with Homebrew. 

Michael

**Comment by ghisvail** [comment] 2016-10-31 19:54
You'd have to tweak `setup.py` manually to support `clang` at the moment.

**Comment by ghisvail** [comment] 2016-10-31 19:56
Duplicate of #51

**Closed** 2016-10-31 19:57 UTC
Labels: duplicate
